mybatis:
  typeAliasesPackage: com.second.hand.trading.server.model
  mapperLocations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_second_hand?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123457
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    time-zone: GMT+8
    date-format: "yyyy-MM-dd HH:mm:ss"
userFilePath: D:/pic
baseUrl: http://localhost:8080
